[default_session]
name = "default"
#path = "~/code/dotfiles"
#default_startup_script = "~/.config/sesh/scripts/default"
#startup_command = "nvim -c \":Telescope find_files\""

#[[session]]
#name = "code ğŸ’»"
#path = "~/Documents/dev"
#startup_script = "~/.config/sesh/scripts/node-pnpm"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "Home ğŸ¡"
path = "~"
startup_command = "l"


[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "second brain ğŸ§ "
path = "~/Documents/notes"
startup_command = "nvim +ObsidianToday"
